// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjXo0eh2DWOCWSny3Tx8iZpZ1SGCo_zco',
    appId: '1:1000313964983:web:adc67ed80c9ea43aac0032',
    messagingSenderId: '1000313964983',
    projectId: 'letmecook-65d6f',
    authDomain: 'letmecook-65d6f.firebaseapp.com',
    storageBucket: 'letmecook-65d6f.appspot.com',
    measurementId: 'G-F59MSFR04L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYZ90zXVmjiyHbrUQ-l8XfgBneUemrIr8',
    appId: '1:1000313964983:android:79a4d119b70f78c1ac0032',
    messagingSenderId: '1000313964983',
    projectId: 'letmecook-65d6f',
    storageBucket: 'letmecook-65d6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAepZsiTf2wEpXO8LDmuND_eDNVfaTmGJo',
    appId: '1:1000313964983:ios:9b28106458ff8baeac0032',
    messagingSenderId: '1000313964983',
    projectId: 'letmecook-65d6f',
    storageBucket: 'letmecook-65d6f.appspot.com',
    iosBundleId: 'com.example.letmecook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAepZsiTf2wEpXO8LDmuND_eDNVfaTmGJo',
    appId: '1:1000313964983:ios:9b28106458ff8baeac0032',
    messagingSenderId: '1000313964983',
    projectId: 'letmecook-65d6f',
    storageBucket: 'letmecook-65d6f.appspot.com',
    iosBundleId: 'com.example.letmecook',
  );
}
